app/simple_pages/routes.py
from flask import Blueprint, render_template
from app.tasks_aka_cookies.models import Task

blueprint = Blueprint('simple_pages', __name__)


@blueprint.route('/')
def index():
    tasks = Task.query.all()
    return render_template('tasks/index.html', tasks=tasks)


@blueprint.route('/studies')
def studies():
     return render_template('studies.html')


@blueprint.route("/private")
def private():
    tasks = Task.query.all()
    return render_template('private.html', tasks=tasks)


@blueprint.route('/user/<username>')
def user_profile(username):
    return render_template('user.html', username=username)

app/templates/tasks/index.html
{% extends 'base.html' %}

{% block title %}To do list{% endblock %}

{% block body %}
  <body class="index-page">
    <h1>Let's tackle our tasks</h1>
    <h2 class="heading">Overview...</h2>

    <div id="div1">
      {% for task in tasks %}
        <p>{{ task.title }} - {{ task.description }}</p>
      {% endfor %}
    </div>
    
    <h2 class="heading">to do</h2>
    <div class="div2">
      <section class="icons position-top flow-vertical">
        <ul>
          <li class="todo-topics">
            <img src="{{ url_for('static', filename='icons/icons8-education.svg') }}" width="62" height="64" loading="lazy"
              alt="">
            <ul>
              <li>
                <h3><strong>studies</strong></h3>
              </li>
              <li>
                <a href="{{ url_for('simple_pages.studies') }}">How are your studies going? Tell me!</a>
              </li>
            </ul>
          </li>
        </ul>
      </section>
      <section class="icons position-top flow-vertical">
        <ul>
          <li class="todo-topics">
            <img src="{{ url_for('static', filename='icons/icons8-fingerprint-scan.svg') }}" alt="">
            <ul>
              <h3>
                <li><strong>private</strong></li>
              </h3>
              <li><a href="{{ url_for('simple_pages.private') }}">What secrets do you want to tell me?I will try to organise
                  your chaos
                  :)</a></li>
            </ul>
          </li>
        </ul>
      </section>
      <section class="icons position-top flow-vertical">
        <ul>
          <li class="todo-topics">
            <img src="{{ url_for('static', filename='icons/icons8-select-all.svg') }}" alt="">
            <ul>
              <h3>
                <li><strong>general</strong></li>
              </h3>
              <li><a href="{{ url_for('tasks_aka_cookies.general') }}"> Here you can write down everything, so your head
                  doesn't get too
                  crowded</a></li>
            </ul>
          </li>
        </ul>
      </section>
    </div>
  </body>
{% endblock %}