app/simple_pages/routes.py
from flask import Blueprint, render_template
from app.tasks_aka_cookies.models import Task

blueprint = Blueprint('simple_pages', __name__)


@blueprint.route('/')
def index():
    tasks = Task.query.all()
    return render_template('tasks/index.html', tasks=tasks)


@blueprint.route('/studies')
def studies():
     return render_template('studies.html')


@blueprint.route("/private")
def private():
    tasks = Task.query.all()
    return render_template('private.html', tasks=tasks)


@blueprint.route('/user/<username>')
def user_profile(username):
    return render_template('user.html', username=username)

app/tasks_aka_cookies/routes.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for, jsonify
from app.tasks_aka_cookies.models import Task, Category
from app.extensions.database import db
from datetime import datetime
# from app.todo_aka_orders.models import Tag, TaskTag, Note
# from app.todo_aka_orders.action.create_task import create_task


blueprint = Blueprint('tasks_aka_cookies', __name__)


@blueprint.route("/general")
def general():
    new_task = Task.query.all()
    return render_template('general.html', tasks=new_task)


@blueprint.before_app_first_request
def create_tables():
    db.create_all()

# @blueprint.route('/')
# def index():
#     return redirect(url_for('tasks'))

# @blueprint.route('/tasks')
# def tasks():
#     tasks = Task.query.all()
#     return render_template('tasks.html', tasks=tasks)


@blueprint.route('/tasks/new', methods=['GET', 'POST'])
def new_task():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        whendue = datetime.strptime(
            request.form['whendue'], '%Y-%m-%d') if request.form['whendue'] else None
        completed = request.form.get('completed') == 'on'
        categories = request.form.getlist('categories')
        task = Task(title=title, description=description,
                    whendue=whendue, completed=completed)
        for category_id in categories:
            category = Category.query.get(category_id)
            task.category.append(category)
        db.session.add(task)
        db.session.commit()
        # render_template('tasks_aka_cookies/new_task.html', categories=categories)
        return redirect('/general')
    categories = Category.query.all()
    # redirecvt to tastk/id/edit
    return render_template('tasks_aka_cookies/new_task.html', categories=categories)


@blueprint.route('/task/<int:id>/edit', methods=['GET', 'POST'])
def edit_task(id):
    task = Task.query.get(id)
    categories = Category.query.all()
    if request.method == 'POST':
        task.title = request.form['title']
        task.description = request.form['description']
        task.whendue = datetime.strptime(
            request.form['whendue'], '%Y-%m-%d') if request.form['whendue'] else None
        task.completed = bool(request.form.get('completed'))
        task.category = []
        categories = request.form.getlist('categories')
        for category_id in categories:
            category = Category.query.get(category_id)
            task.category.append(category)
        db.session.commit()
        return redirect('/general')
        # return redirect(url_for('tasks_aka_cookies.new_task'))
    return render_template('edit_task.html', task=task, categories=categories)


@blueprint.route('/tasks/<int:id>/delete', methods=['DELETE', 'POST'])
def delete_task(id):
    task = Task.query.get(id)
    if not task:
        return jsonify({'error': 'Task not found'}), 404
    db.session.delete(task)
    db.session.commit()
    # if request.method == 'POST':
    #     return jsonify({'message': 'Task deleted'})
    # else:
    return redirect(url_for('tasks_aka_cookies.general'))
    # return redirect('/general')
    # return render_template('delete_task.html', task=task)


@blueprint.route('/tasks/list')
def get_list():
    tasks = Task.query.all()
    return render_template('task_detail.html', tasks=tasks)


# @blueprint.route('/tasks/<slug>')
# def task(slug):
#      task = Task.query.filter_by(slug=slug).first_or_404()
#      return render_template('tasks/show.html', task=task)

# @blueprint.route('/tasks')
# def tasks():
#      page_number = request.args.get('page', 1, type=int)
#      tasks_pagination = Task.query.paginate(page_number, current_app.config['COOKIES_PER_PAGE'])
#      return render_template('tasks/index.html', tasks_pagination=tasks_pagination)


# @blueprint.route('/tasks')
# def task_list():
#      page = request.args.get('page', 1, type=int)
#      per_page = request.args.get('per_page', 10, type=int)
#      tasks = Task.query.paginate(page=page, per_page=per_page)
#      return render_template('todo/task_list.html', tasks=tasks, url=request.url)


# @blueprint.route('/task/<int:task_id>')
# def task_detail(task_id):
#       task = Task.query.get(task_id)
#       return render_template('task_detail.html', task=task)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Viola's private To Do-List{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  {% endblock %}
</head>
<body>
  {% block body %}<title>Viola's private To Do-List</title>{% endblock %}
</body>
</html>

app/templates/delete_task.html
<!-- {% extends 'base.html' %}

{% block body %}
  <h1>Delete Task</h1>
  <p>Are you sure you want to delete this task?</p>
  <p>Task: {{ task.title }}</p>
  <form method="post" action="{{ url_for('tasks_aka_cookies.delete_task', id=task.id) }}" id="delete-task-form">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Yes, delete it">
  </form>
  <p><a href="{{ url_for('tasks_aka_cookies.index') }}">Cancel</a></p>
  <script>
    const form = document.querySelector('#delete-task-form');
    form.addEventListener('submit', (event) => {
      event.preventDefault();
      const url = form.getAttribute('action');
      const method = form.querySelector('input[name="_method"]').value;
      fetch(url, { method })
        .then(response => {
          if (response.redirected) {
            window.location.href = response.url;
          }
        });
    });
  </script>

{% endblock %} -->

app/templates/edit_task.html
{% extends 'base.html'%}

{% block body %}
<h1>Edit Task</h1>
<form method="post" action="{{ url_for('tasks_aka_cookies.edit_task', id=task.id) }}">
  <label for="title">Title:</label>
  <input type="text" id="title" name="title" value="{{ task.title }}" required>
  <br>
  <label for="description">Description:</label>
  <textarea id="description" name="description" rows="5" required>{{ task.description }}</textarea>
  <br>
  <label for="char_count">Character Count:</label>
  <span id="char_count">0</span> / 100
  <br>
  <label for="whendue">Due Date:</label>
  <input type="date" id="whendue" name="whendue"
    value="{{ task.whendue.strftime('%Y-%m-%d') if task.whendue else '' }}">
  <br>
  <label for="completed">Completed:</label>
  <input type="checkbox" id="completed" name="completed" {% if task.completed %}checked{% endif %}>
  <br>
  <label for="categories">Categories:</label>
  {% for category in categories %}
  <input type="checkbox" id="category_{{ category.id }}" name="categories" value="{{ category.id }}" {% if category in
    task.category %}checked{% endif %}>
  <label for="category_{{ category.id }}">{{ category.name }}</label>
  <br>
  {% endfor %}
  <br>
  <button type="submit">Save</button>
</form>

<script>
  var description = document.getElementById("description");
  var char_count = document.getElementById("char_count");
  
  description.addEventListener("keyup", function(){
    var length = description.value.length;
    char_count.innerText = length;
    if (length > 100){
      description.value = description.value.substring(0, 100);
      char_count.innerText = 100; 
    }
  });
  
  </script>

{% endblock %}

app/templates/general.html
{% extends 'base.html'%}

{% block title %}Viola's private To Do-List{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('ul.task-list li').hover(function() {
        var taskTitle = $(this).find('.task-title').text();
        var taskDescription = $(this).find('.task-description').text();
        $('#task-popup .title').text(taskTitle);
        $('#task-popup .description').text(taskDescription);
        $('#task-popup').show();
      }, function() {
        $('#task-popup').hide();
      });
    });
  </script>
{% endblock %}

{% block body %}
  <h1>All Tasks</h1>
  <a href="{{ url_for('tasks_aka_cookies.new_task') }}" class="button" style="margin-bottom:10px;">New Task</a>
  <ul class="task-list">
    {% for task in tasks %}
      <li>
        <div class="task-title">
          <a href="/task/{{ task.id }}">{{ task.title }}</a>
        </div>
        <div class="form-group">
          <form action="/task/{{ task.id }}/edit" method="get">
            <button>Edit</button>
          </form>
        </div>
        <div class="form-group">
          <form action="/tasks/{{ task.id }}/delete" method="POST">
            <input type="hidden" name="_method" value="DELETE">
           <button>Delete</button>
          </form>
        </div>
        <div class="task-description" style="display: none;">
          {{ task.description }}
        </div>
      </li>
    {% endfor %}
  </ul>
  <a href="{{ url_for('simple_pages.index') }}" class="button">Main Page</a>
  <div id="task-popup">
    <div class="title"></div>
    <div class="description"></div>
  </div>
{% endblock %}

app/templates/new_task.html
{% extends 'base.html' %}

{% block content %}
  <h1>New Task</h1>
  <form method="post">
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" required>
    <br>
    <label for="description">Description:</label>
    <textarea id="description" name="description" rows="5" required></textarea>
    <br>
    <label for="whendue">Due Date:</label>
    <input type="date" id="whendue" name="whendue">
    <br>
    <label for="completed">Completed:</label>
    <input type="checkbox" id="completed" name="completed">
    <br>
    <label for="categories">Categories:</label>
    {% for category in categories %}
      <input type="checkbox" id="category_{{ category.id }}" name="categories" value="{{ category.id }}">
      <label for="category_{{ category.id }}">{{ category.name }}</label>
      <br>
    {% endfor %}
    <br>
    <button type="submit">Create</button>
  </form>
{% endblock %}

app/templates/private.html
{% extends 'base.html' %}

{% block title %}Viola's private To Do-List{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
    $('ul.task-list li').hover(function () {
      var taskTitle = $(this).find('.task-title').text();
      var taskDescription = $(this).find('.task-description').text();
      $('#task-popup .title').text(taskTitle);
      $('#task-popup .description').text(taskDescription);
      $('#task-popup').show();
    }, function () {
      $('#task-popup').hide();
    });
  });
</script>
{% endblock %}


{% block body %}

<h1>What secrets do you want to tell me?</h1>
<h3>I will try to organise your chaos :)</h3>
<a href="{{ url_for('tasks_aka_cookies.new_task') }}" class="button" style="margin-bottom:10px;">New Task</a>
<ul class="task-list">
  {% for task in tasks %}
  <li>
    <div class="task-title">
      <a href="/task/{{ task.id }}">{{ task.title }}</a>
    </div>
    <div class="form-group">
      <form action="/task/{{ task.id }}/edit" method="get">
        <button>Edit</button>
      </form>
    </div>
    <div class="form-group">
      <form action="/tasks/{{ task.id }}/delete" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <button>Delete</button>
      </form>
    </div>
    <div class="task-description" style="display: none;">
      {{ task.description }}
    </div>
  </li>
  {% endfor %}
</ul>
<a href="{{ url_for('simple_pages.index') }}" class="button">Main Page</a>
<div id="task-popup">
  <div class="title"></div>
  <div class="description"></div>
</div>
{% endblock %}

app/templates/studies.html
{% extends 'base.html'%}

{% block head %}
   {{ super() }}
{% endblock %}

{%block title%}Viola's private To Do-List{%endblock%}

{%block body%}
    <h1>How are your studies going? Tell me!</h1>
    <h3>What kind of tasks are you going to do?</h3>
    <div class="container">
        <section class="icons position-top flow-vertical">
            <ul>
                <li class="studies-deadlines">
                    <img src="../static/icons/icons8-deadline.svg" alt="">
                    <ul>
                        <li>
                            <a href="#">assignments/deadlines</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </section>
        <section class="icons position-top flow-vertical">
            <ul>
                <li class="studies-files">
                    <img src="../static/icons/icons8-resume-website.svg" alt="">
                    <ul>
                        <li><a href="#">resources/files</a></li>
                    </ul>
                </li>
            </ul>
        </section>
        <section class="icons position-top flow-vertical">
            <ul>
                <li class="studies-documentation">
                    <img src="../static/icons/icons8-business-documentation.svg" alt="">
                    <ul>
                        <li><a href="#">documentation</a></li>
                </li>
            </ul>
        </section>
    </div>
    <a href="{{ url_for('simple_pages.index') }}" class="button">main page</a>
  

{%endblock%}

app/templates/task_detail.html
{% extends 'base.html'%}

{% block title %}Viola's private To Do-List{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block body %}
  <head>
    <title>{{ task.title }}</title>
  </head>
  <body>
    <h1>{{ task.title }}</h1>
    <p>{{ task.description }}</p>
    <p>Due: {{ task.whendue }}</p>
    {% if task.completed %}
      <p>Completed</p>
    {% else %}
      <p>Incomplete</p>
    {% endif %}
    {% if task.category %}
      <p>Category: {{ task.category.name }}</p>
    {% endif %}
    <div class="edit-button">
      <a href="{{ url_for('tasks_aka_cookies.edit_task', id=task.id) }}">Edit</a>
      <form action="{{ url_for('tasks_aka_cookies.delete_task', id=task.id) }}" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <button type="submit">Delete</button>
      </form>
    </div>
    {% if task %}
        {% if task.has_prev %}
            <a href="{{ url_for('action.task_list', page=tasks.prev_num) }}">Previous</a>
        {% endif %}
    {% endif %}
     
    {% if task and task.has_next %}
        <a href="{{ url_for('action.task_list', page=tasks.next_num) }}">Next</a>
    {% endif %}
  </body>

  {%endblock%} 

app/templates/user.html
<!DOCTYPE html>
<html>

<head>
    <title>Viola's private To Do-List</title>
    <h1> Hi </h1>
</head>